# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8b85c5f6b3cb246a1babcb145b53c0f2f70c642ae786040497e408a9cba9f1075c0106ee09f054ba1cd7b8d0390398e54afabf37785ab436e3fadb6077872bfc

test:
  secret_key_base: 5cf2b5b4a01b07a904bf03d7e1029fb116ed95a88cdc1330fd6f003feae874fd31d85eb54357feba054f777bfc03ebe29601b6a13b88708d2feb8b160a1a8a8a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
